version: "3"
services:
     docker-base-be:
          image: base-be
          restart: always
          environment:
               PORT: 5000
               MONGODB_URL: mongodb://mongo:27017/test?readPreference=primary&appname=MongoDB%20Compass%20Community&ssl=false
          build: .
          volumes:
               - .:/docker-base-be # blind file change
          ports:
               - 5000:5000
          links:
               - mongo
     mongo:
          image: mongo:latest
          ports:
               - 27017:27017
